### ISSUE TITLE
need updated mbari/strongsort-yolov5 in ecr repositories

### ISSUE THREAD

**Issue by duane-edgington** [mbari-org/deepsea-ai#31]
because of a update in a dependency, need updated mbari/strongsort-yolov5 in the ecr repositories corresponding to the AWS accounts where this package is run. example 901103-bio AWS ECR repo. 

https://hub.docker.com/repository/docker/mbari/strongsort-yolov5/general is currently at 1.10.0 which fails when run from doris.shore.mbari.org 

Traceback (most recent call last):
  File "track.py", line 322, in <module>
    main(opt)
  File "track.py", line 317, in main
    run(**vars(opt))
  File "/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 121, in run
    StrongSORT(
  File "/app/yolo_tracking/strong_sort/strong_sort.py", line 46, in __init__
    gdown.download(model_url, str(model_weights), quiet=False)
  File "/env/lib/python3.8/site-packages/gdown/download.py", line 259, in download
    filename_from_url = m.groups()[0]

**Comment by duane-edgington** [comment]
Roger. The docker tag has not been updated with the new version. I don't think it has been pushed to docker hub.

**Comment by duane-edgington** [comment]
This was completed by updating the dependency version (node.js to lts/*) and restarting the github actions. Then pulled to ECR registry on AWS using the deepsea-ai setup --mirror command as indicated, once for each AWS account.
